parameters:

    # Queue worker Prefix
    worker_bundle.queue.prefix: worker

    # Path to log
    worker_bundle.worker.current.logpath: app/logs/worker/current
    worker_bundle.worker.finished.logpath: app/logs/worker/finished

services:
    app.worker.queuenamegenerator:
        class: WorkerBundle\Utils\QueueNameGenerator
        arguments: [%worker_bundle.queue.prefix%]
    app.utils.worker:
        class: WorkerBundle\Utils\Worker
        arguments: [%kernel.root_dir%]
    app.worker.log:
        class: WorkerBundle\Utils\WorkerLogManager
        arguments: [%worker_bundle.worker.current.logpath%,%worker_bundle.worker.finished.logpath%]
    app.worker.manager:
        class: WorkerBundle\Utils\WorkerManager
        arguments: [%worker.config%]